project:
  machine_name: mpotter
  prefix: mpotter
  human_name: 'MPotter Test'
  profile:
    name: standard
  local:
    protocol: http
    hostname: 'www.irs.vm'
git:
  default_branch: master
  remotes:
    - "mpottertest@svn-6377.devcloud.hosting.acquia.com:mpottertest.git"
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend-setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend-build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
import: null
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]

